# Generated by Django 4.1.3 on 2022-12-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_category_name_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
